# Docker Compose override for development
# This file provides additional development-specific configurations

services:
  mainote-server:
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    ports:
      - "${APP_PORT}:${APP_PORT}"
    labels:
      - "traefik.enable=false"
      - "dev.service=mainote-server"

  mainote-bot:
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    labels:
      - "traefik.enable=false"
      - "dev.service=mainote-bot" 