# fly.toml app configuration file generated for mainote-bot on 2025-05-18T23:15:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mainote-bot'
primary_region = 'cdg'

[build]

[env]
  PORT = "8080"
  GO_BACKEND_PORT = "8081"
  GO_BACKEND_URL = "http://localhost:8081"

# Main service (Python bot webhook endpoint)
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

# Optional: Expose Go backend externally (for health checks, monitoring, etc.)
# If you need external access to the Go backend, uncomment this section:
# [[services]]
#   internal_port = 8080
#   protocol = "tcp"
#   
#   [[services.ports]]
#     port = 8080
#     handlers = ["http"]
#   
#   [services.concurrency]
#     type = "connections"
#     hard_limit = 25
#     soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
