# Reusable Parameters

# Path Parameters
NoteIdPathParam:
  name: noteId
  in: path
  required: true
  description: Unique identifier of the note
  schema:
    type: string
    format: uuid
    example: "550e8400-e29b-41d4-a716-446655440000"

# Query Parameters
ChatIdQueryParam:
  name: chat_id
  in: query
  required: true
  description: Telegram chat ID to filter notes by
  schema:
    type: string
    example: "123456789"
    maxLength: 50

CategoryQueryParam:
  name: category
  in: query
  required: false
  description: Filter notes by category
  schema:
    $ref: 'schemas.yaml#/NoteCategory'
  example: "idea"

StatusQueryParam:
  name: status
  in: query
  required: false
  description: Filter notes by status
  schema:
    $ref: 'schemas.yaml#/NoteStatus'
  example: "active"

LimitQueryParam:
  name: limit
  in: query
  required: false
  description: Maximum number of notes to return
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 10
    example: 10

OffsetQueryParam:
  name: offset
  in: query
  required: false
  description: Number of notes to skip for pagination
  schema:
    type: integer
    minimum: 0
    default: 0
    example: 0

# Header Parameters
ContentTypeHeader:
  name: Content-Type
  in: header
  required: true
  description: Content type of the request body
  schema:
    type: string
    enum:
      - application/json
    default: application/json
